### ISSUE TITLE
Design Database

### ISSUE THREAD

**Issue by tisana** [dst-hackathon/fpv-api-spring#1]
Core tables
- Employee Information
- Desk Information
- Floor Information

**Comment by starkhorn** [comment]
I just thought that how are we going to handle multiple teams changing data on the same database.

For example, if team A tests their application by assigning an employee to a desk on floor 16, if the change happens on the same database, team B would see the change as well and could confuse them.

So, the question might be, should we provide multiple databases (or schemas) to support multiple teams. Or, we could just provide only query APIs (read) but not mutation APIs (create, update, delete) ?

Or, we do not provide centralized APIs server but each team will require to clone / fork this project and run it on their own development server.

What are your thoughts?

**Comment by tisana** [comment]
During each team development, it might be easier to let each team clone the project and run on their local machine. 
For centralize server we may set a schedule to "reset" data (eg. every 2 hours)

**Comment by tisana** [comment]
Looking into LDAP dumped data, there are several fields that are not used in the application. Should we add those fields into our design or should we only focus on the fields we are really use?

**Comment by starkhorn** [comment]
I'd say focus on what we really use to save time 55.

About the design, I think it might be easier if the user could create multiple versions of a floor plan. Let's say, 17th floor plan for November and December 2016, this is because we need to create the seat change report and it would be easier to just compare plans -- well, think of it like AWD process flow versioning.

What do you think?

**Comment by mekeerati** [comment]
DST JAN 2016 (Plan)
- RSU tower (Tower)
  - 6 (Floor)
    - 601 (Desk)
    - 602
    - 603
  - 15
  - 16
  - 17
  - 18
- BW
  - 9
  - 10
